default: &default
  adapter: sqlite3
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: articles_development

test:
  <<: *default
  database: articles_test

production:
  <<: *default
  database: AppCRUD_production
  username: AppCRUD
  password: <%= ENV['APPCRUD_DATABASE_PASSWORD'] %>
