height: 500
menubar: false
toolbar:
  - undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify| link image | bullist numlist outdent indent | removeformat | help
plugins:
  - advlist autolink lists link image charmap print preview anchor uploadimage
  - searchreplace visualblocks code fullscreen
  - insertdatetime media table paste code help wordcount